version: 2

jobs:
  install:
    docker:
      - image: circleci/node:8.7

    steps:
      - checkout

      - restore_cache:
          key: node-deps-{{ checksum "package-lock.json" }}-{{ checksum "package.json" }}
      - run:
          name: Install node dependencies
          command: npm i --no-package-lock
      - save_cache:
          key: node-deps-{{ checksum "package-lock.json" }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules

  test:
    docker:
      - image: circleci/node:8.7-browsers

    steps:
      - checkout

      - restore_cache:
          key: node-deps-{{ checksum "package-lock.json" }}-{{ checksum "package.json" }}
      - run:
          name: Test
          command: npm test

  desploy:
    docker:
      - image: circleci/node:8.7

    steps:
      - checkout
      - restore_cache:
          key: node-deps-{{ checksum "package-lock.json" }}-{{ checksum "package.json" }}
      - run:
          name: Ship theme files
          command: |
            if [[ "${CIRCLE_BRANCH}" == "master" ]]; then
              env | sed -n 's/^DEMO_//p' > .env
              export AWS_BUCKET=$DEMO_AWS_BUCKET
              export AWS_PREFIX=$DEMO_AWS_PREFIX
            elif grep -q "v[0-9]\+\.[0-9]\+\.[0-9]\+" <<< "$CIRCLE_TAG"; then
              env | sed -n 's/^PROD_//p' > .env
              export AWS_BUCKET=$PROD_AWS_BUCKET
              export AWS_PREFIX=$PROD_AWS_PREFIX
            fi
            aws s3 sync ./json/ s3://"$AWS_BUCKET"/"$AWS_PREFIX" --cache-control "max-age=0, no-cache"

      - run:
          name: Generate Theme Index
          command: |
            npm run generate
            aws s3 sync ./index.json s3://"$AWS_BUCKET"/"$AWS_PREFIX" --cache-control "max-age=0, no-cache"
workflows:
  version: 2
  install-test-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - test:
          filters:
            tags:
              only: /.*/
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v[0-9]\.[0-9]\.[0-9]+/
            branches:
              only: master
